// Copyright (c) Vito Domenico Tagliente
// automatically generated by the compiler, do not modify
#pragma once

#include <vdtreflect/runtime.h>

template <>
struct EnumType<enum class TestEnum>
{
    static const char* name();
    static const  enum_values_t& values();
};

struct __TestEnumEnum : RegisteredInEnumFactory<enum class TestEnum>
{
    static bool registered() { return value; };
};

template <>
struct EnumType<enum class UserRole>
{
    static const char* name();
    static const  enum_values_t& values();
};

struct __UserRoleEnum : RegisteredInEnumFactory<enum class UserRole>
{
    static bool registered() { return value; };
};

template <>
struct EnumType<enum class ApplicationMode>
{
    static const char* name();
    static const  enum_values_t& values();
};

struct __ApplicationModeEnum : RegisteredInEnumFactory<enum class ApplicationMode>
{
    static bool registered() { return value; };
};

struct __FooType : RegisteredInTypeFactory<__FooType>
{
    __FooType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

struct __PooType : RegisteredInTypeFactory<__PooType>
{
    __PooType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

struct __UserType : RegisteredInTypeFactory<__UserType>
{
    __UserType() = delete;

    static const TypeDefinition& type();
    static bool registered() { return value; };
};

